title: Bureautique
levels:
  - secondaire-superieur
updated_by: 409cbafe-f643-4145-b952-25177427041d
updated_at: 1715086133
blueprint: courses_category
category_levels:
  - secondaire-superieur
icon: Bureautique
