title: 'Developpement personnel'
icon: 'Developpement personnel'
updated_by: 409cbafe-f643-4145-b952-25177427041d
updated_at: 1712683423
blueprint: courses_category
levels:
  - secondaire-superieur
category_levels:
  - secondaire-superieur
