title: Langues
icon: Langues
updated_by: 409cbafe-f643-4145-b952-25177427041d
updated_at: 1712683437
levels:
  - secondaire-inferieur
  - secondaire-superieur
  - superieur-type-court
blueprint: courses_category
category_levels:
  - secondaire-inferieur
  - secondaire-superieur
  - superieur-type-court
