title: Paramedicale
icon: Paramedicale
updated_by: 409cbafe-f643-4145-b952-25177427041d
updated_at: 1712683457
blueprint: courses_category
levels:
  - secondaire-superieur
category_levels:
  - secondaire-superieur
